// <auto-generated />
using AirplaneFactory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirplaneFactory.Migrations.Migrations
{
    [DbContext(typeof(AirplaneDbContext))]
    [Migration("20201125030806_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AirplaneFactory.Domain.Models.AirplaneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirplaneType")
                        .HasColumnType("int");

                    b.Property<int>("MotorQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("airplanes");
                });

            modelBuilder.Entity("AirplaneFactory.Domain.Models.MotorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<int>("MotorType")
                        .HasColumnType("int");

                    b.Property<bool>("Running")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneId");

                    b.ToTable("motors");
                });

            modelBuilder.Entity("AirplaneFactory.Domain.Models.MotorModel", b =>
                {
                    b.HasOne("AirplaneFactory.Domain.Models.AirplaneModel", "Airplane")
                        .WithMany("Motors")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
